ClassTrail/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('pages.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

pages/urls.py
from django.urls import path
from .import  views

urlpatterns=[
     path('',views.index, name='index'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.conf import settings
from datetime import date
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator, FileExtensionValidator
from django import template
from datetime import datetime
from django.core.exceptions import ValidationError

# Create your models here.

#model for the user, uses 2 boolean fields to define user types.
class User(AbstractUser):
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)

#teacher user
class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    teacher_name = models.CharField(max_length=100)

#classroom model, teacher foreignkey is the teacher who created the classroom. Teachers can have many classrooms.
class Classroom(models.Model):
    classroom_subject = models.CharField(max_length=100)
    classroom_code = models.CharField(max_length= 5, default = '00000')
    teacher = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    classroom_description = models.TextField()
    def __str__(self):
        return self.classroom_subject

    def get_student(self):
        return 

    def get_classroom(self):
        workitems = WorkItem.objects.filter(classroom = self).count()
        return workitems

#student model, classes field is the relationship a student has with classrooms
class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    student_name = models.CharField(max_length=100)
    classes = models.ManyToManyField(Classroom, blank = True)

class WorkItem(models.Model):
    classroom = models.ForeignKey(Classroom, on_delete=models.CASCADE)
    work_description = models.TextField()

    date_assigned = models.DateField(auto_now_add=True, blank=True)
    time_assigned = models.TimeField(auto_now_add=True, blank=True)

    @property
    def get_age(self):
        return int((timezone.now() - self.date_assigned).total_seconds()/3600)

    def get_classroom(self):
        return self.classroom.classroom_subject

    def get_date(self):
        return self.date_assigned

class UserUpload(models.Model):
    name = models.CharField(max_length= 30)
    picture = models.FileField(upload_to='media/')
    date = models.DateField()
    time_assigned = models.TimeField(auto_now_add=True, blank=True)
    student = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    classtrail_bool = models.BooleanField('Add to ClassTrail', default=True)
    submission = models.ForeignKey(WorkItem, null = True, on_delete=models.CASCADE)
    grade = models.IntegerField(null = True, validators=[
            MaxValueValidator(100),
            MinValueValidator(1)
        ])

    def delete(self):
        self.picture.delete(save=False)
        super().delete()

    @property
    def is_late(self):
        if self.submission is not None:
            submission_date = datetime.combine(self.date, self.submission.time_assigned)
            return submission_date
            


    

templates/add_classtrail.html
{% extends 'base.html' %}
{% block content %}

    <div class="jumbotron">
        <div class="container text-center">
          <h1>Add content to ClassTrail</h1>      
        </div>
    </div>

    {% load crispy_forms_tags %}
    <div class="card-body">
    {{ form.media }}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
 
        <input type="submit" value="Submit">
    </form>

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
        {% endfor %}
    </ul>
    {% endif %}
</div>
{% endblock %}

templates/assign_work.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
    <title>ClassTrail</title>

    <style>
        /* Remove the navbar's default margin-bottom and rounded borders */ 
        .navbar {
        margin-bottom: 0;
        border-radius: 0;
        }

        .jumbotron {
        height: 10vw;

        }
        
        table, td {
        border: 1px solid black;
        }
        
        /* Add a gray background color and some padding to the footer */
        footer {
        background-color: #f2f2f2;
        padding: 25px;
        }
    
    .row [class*="col-"]{
        margin-bottom: -99999px;
        padding-bottom: 99999px;
    }
    
    .row{
        overflow: hidden; 
    }
    .product .img-responsive {
        margin: 0 auto;
    }
    
    img {
        width: 200px; /* You can set the dimensions to whatever you want */
        height: 200px;
        object-fit: cover;
    margin: auto;
    }
    
        .hoverTable{
        width:100%; 
        border-collapse:collapse; 
        margin-bottom: 5vw;
    }
    .hoverTable td{ 
        padding:7px; border:black 1px solid;
    }
    .hoverTable th{ 
        padding:7px; border:black 1px solid;
    }
    /* Define the default color for all the table rows */
    .hoverTable tr{
        background: #eee;
    }
    /* Define the hover highlight color for the table row */
        .hoverTable tr:hover {
            background-color: #b8d1f3;
        }
    
    #myCarousel{
        margin-bottom: 5vw;
    }

    .add_button{
      margin: 1vw;
    }
    </style>


</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'index' %}">ClassTrail</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
        {% if user.is_authenticated and user.is_teacher %}
        <li class="nav-item active"><a class="nav-link" href="{% url 'teacher_hub' %}">Teacher Hub</a></li>
        {% endif %}
        {% if user.is_authenticated and user.is_student %}
        <li class="nav-item active"><a class="nav-link" href="{% url 'student_hub' %}">Student Hub</a></li>
        {% endif %}
        
        </ul>
        <span class="navbar-text">
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated%}
            <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
            {%else%}
            <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
            <li><a href="{% url 'register' %}"><span class="glyphicon glyphicon-log-in"></span> Register</a></li>
            {% endif %}
            </ul>
        </span>
    </div>
    </nav>

    <div class="jumbotron">
        <div class="container text-center">
          <h1>Assign work</h1>      
        </div>
    </div>

    <div class="alert alert-{{ message.tags }}">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            {% if message.tags == "success" %} <div class="alert alert-success " role="alert"> {% endif %}
            {% if message.tags == "error" %} <div class="alert alert-danger" role="alert"> {% endif %}
                {{message}}
              </div>
            {% endfor %}
        </ul>
        {% endif %}
    </div>

    <a href="{% url 'teacher_work_feed' %}" class="add_button btn btn-outline-primary" role="button">View Work Assigned</a>


    <section>
        <div class="container">
          <div class="row">
            <div class="col-md-6 mx-auto">
              <div class="card">
                <div class="card-header text-black">
                </div>
                <div class="card-body">
                    {% load crispy_forms_tags %}

                    {% block content %}
                    <form action="." method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <input type="submit" value="Submit">
                    </form>
                    {% endblock %}
                
                 </div>
                    </div>   
                </div>
              </div>
            </div>
        </div>
      </section>

        <br>

      <div class = "footer navbar-fixed-bottom"></div>

</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>

    <title>ClassTrail</title>

    <style>
      /* Remove the navbar's default margin-bottom and rounded borders */ 
      .navbar {
        margin-bottom: 0;
        border-radius: 0;
      }

      .jumbotron {
        height: 10vw;

      }
      
      table, td {
      border: 1px solid black;
      }
      
      /* Add a gray background color and some padding to the footer */
      footer {
        background-color: #f2f2f2;
        padding: 25px;
      }
    
    .row [class*="col-"]{
      margin-bottom: -99999px;
      padding-bottom: 99999px;
    }
  
    .row{
      overflow: hidden; 
    }
    .product .img-responsive {
      margin: 0 auto;
  }
  
  img {
      width: 200px; /* You can set the dimensions to whatever you want */
      height: 200px;
      object-fit: cover;
    margin: auto;
  }
  
      .hoverTable{
      width:100%; 
      border-collapse:collapse; 
      margin-bottom: 5vw;
    }
    .hoverTable td{ 
      padding:7px; border:black 1px solid;
    }
    .hoverTable th{ 
      padding:7px; border:black 1px solid;
    }
    /* Define the default color for all the table rows */
    .hoverTable tr{
      background: #eee;
    }
    /* Define the hover highlight color for the table row */
      .hoverTable tr:hover {
            background-color: #b8d1f3;
      }

      .img-container {
        height: 70vh;
        overflow: auto;
        }

        .img-container img {
        width: auto;
        height: 70vh;
        display: block;
        margin-left: auto;
        margin-right: auto;
        }

        .footer {
            height: 70vh;
            background: #eee;
        }

        .student_hub .card-body{ 
          height: 30vh; 
  
        }
        .student_hub .card{
          width: 100%;
        }

        .teacher_hub .card{
          width: 100%;
        }

        .add_button{
      margin: 1vw;
    }

    .center{
        margin: auto;
        width: 50%;
    }

    .classtrail_list img {
      width: 200px; /* You can set the dimensions to whatever you want */
      object-fit: cover;
    margin: auto;
  }

  .alert {
    opacity: 1;
    visibility: visible;
    transform: translateX(0px);
    transition: visibility 0s, opacity 250ms, transform 250ms;

    }
    .alert.hide {
    position: relative;
    opacity: 0;
    visibility: hidden;
    transform: translateX(-10px); 
    transition: visibility 0s 250ms, opacity 250ms, transform 250ms;
}




    </style>
</head>
<body>  
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'index' %}">ClassTrail</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        {% if user.is_authenticated and user.is_teacher %}
        <li class="nav-item active"><a class="nav-link" href="{% url 'teacher_hub' %}">Teacher Hub</a></li>
        {% endif %}
        {% if user.is_authenticated and user.is_student %}
        <li class="nav-item active"><a class="nav-link" href="{% url 'student_hub' %}">Student Hub</a></li>
        {% endif %}
        
      </ul>
      <span class="navbar-text">
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated%}
            <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
            {%else%}
            <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
            <li><a href="{% url 'register' %}"><span class="glyphicon glyphicon-log-in"></span> Register</a></li>
            {% endif %}
          </ul>
      </span>
    </div>
  </nav>
  {% block content %}
  {% endblock %}

</body>
</html>

templates/classroom.html
{% extends 'base.html' %}
{% block content %}

    <div class="jumbotron">
        <div class="container text-center">
          <h1>{{classroom.classroom_subject}}</h1>      
        </div>
    </div>

{% if user.is_authenticated and user.is_teacher %}
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
  Delete Classroom
</button>
{% endif %}





    <h1>Teacher Name: {{classroom.teacher.first_name}} {{classroom.teacher.last_name}}</h1> 
   
{% if user.is_authenticated and user.is_teacher %}

    <h1>Classroom Id: {{classroom.id}}</h1>
    <h1>Classroom Code: {{classroom.classroom_code}}</h1>
{% endif %}



   {% for work in work_list %}
    <h1>{{ work.date_assigned }}</h1>
    {% endfor %}

    <div class="modal fade" id="myModal">
      <div class="modal-dialog">
        <div class="modal-content">
        
          <!-- Modal Header -->
          <div class="modal-header">
            <h4 class="modal-title">Delete classroom: {{ classroom.classroom_subject }} </h4>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
          </div>
          
          <!-- Modal body -->
          <div class="modal-body">
            <p>Are you sure you want to delete "{{ classroom.classroom_subject }}"?</p>
          </div>
          
          <!-- Modal footer -->
          <div class="modal-footer">
            <a  href="{% url 'delete_classroom' classroom.id %}" class="btn btn-outline-danger" role="button">Confirm Delete</a>
          </div>
          
        </div>
      </div>
    </div>
{% endblock %}

templates/edit_work_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  
    <title>ClassTrail</title>

    <style>
      /* Remove the navbar's default margin-bottom and rounded borders */ 
      .navbar {
        margin-bottom: 0;
        border-radius: 0;
      }

      
      table, td {
      border: 1px solid black;
      }
      
      /* Add a gray background color and some padding to the footer */
      footer {
        background-color: #f2f2f2;
        padding: 25px;
      }
    
    .row [class*="col-"]{
      margin-bottom: -99999px;
      padding-bottom: 99999px;
    }
  
    .row{
      overflow: hidden; 
    }
    .product .img-responsive {
      margin: 0 auto;
  }
  
  img {
      width: 200px; /* You can set the dimensions to whatever you want */
      height: 200px;
      object-fit: cover;
    margin: auto;
  }
  
      .hoverTable{
      width:100%; 
      border-collapse:collapse; 
      margin-bottom: 5vw;
    }
    .hoverTable td{ 
      padding:7px; border:black 1px solid;
    }
    .hoverTable th{ 
      padding:7px; border:black 1px solid;
    }
    /* Define the default color for all the table rows */
    .hoverTable tr{
      background: #eee;
    }
    /* Define the hover highlight color for the table row */
      .hoverTable tr:hover {
            background-color: #b8d1f3;
      }
      
      .img-container {
        height: 70vh;
        overflow: auto;
        }

        .img-container img {
        width: 55%;
        height: auto;
        display: block;
        margin-left: auto;
        margin-right: auto;
        }

 
    </style>

</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'index' %}">ClassTrail</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        {% if user.is_authenticated and user.is_teacher %}
        <li class="nav-item active"><a class="nav-link" href="{% url 'teacher_hub' %}">Teacher Hub</a></li>
        {% endif %}
        {% if user.is_authenticated and user.is_student %}
        <li class="nav-item active"><a class="nav-link" href="{% url 'student_hub' %}">Student Hub</a></li>
        {% endif %}
        
      </ul>
      <span class="navbar-text">
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated%}
            <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
            {%else%}
            <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
            <li><a href="{% url 'register' %}"><span class="glyphicon glyphicon-log-in"></span> Register</a></li>
            {% endif %}
          </ul>
      </span>
    </div>
  </nav>

    <div class="jumbotron">
        <div class="container text-center">
          <h1>{{ object.classroom }}'s work {{ object.date_assigned }}</h1>      
        </div>
    </div>

    <div class="alert alert-{{ message.tags }}">
      {% if messages %}
      <ul class="messages">
          {% for message in messages %}
          {% if message.tags == "success" %} <div class="alert alert-success " role="alert"> {% endif %}
          {% if message.tags == "error" %} <div class="alert alert-danger" role="alert"> {% endif %}
              {{message}}
            </div>
          {% endfor %}
      </ul>
      {% endif %}
  </div>

    <section>
        <div class="container">
          <div class="row">
            <div class="col-md-6 mx-auto">
              <div class="card">
                <div class="card-header text-black">
                </div>
                <div class="card-body">
                    {% load crispy_forms_tags %}

                    {% block content %}
                    <form action="." method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <input type="submit" value="Submit">
                    </form>
                    {% endblock %}
                
                 </div>
                    </div>   
                </div>
              </div>
            </div>
        </div>
      </section>

</body>
</html>

templates/grade_work.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
    <title>ClassTrail</title>

    <style>
      /* Remove the navbar's default margin-bottom and rounded borders */ 
      .navbar {
        margin-bottom: 0;
        border-radius: 0;
      }

      .jumbotron {
        height: 10vw;

      }
      
      table, td {
      border: 1px solid black;
      }
      
      /* Add a gray background color and some padding to the footer */
      footer {
        background-color: #f2f2f2;
        padding: 25px;
      }
    
    .row [class*="col-"]{
      margin-bottom: -99999px;
      padding-bottom: 99999px;
    }
  
    .row{
      overflow: hidden; 
    }
    .product .img-responsive {
      margin: 0 auto;
  }
  
  img {
      width: 200px; /* You can set the dimensions to whatever you want */
      height: 200px;
      object-fit: cover;
    margin: auto;
  }
  
      .hoverTable{
      width:100%; 
      border-collapse:collapse; 
      margin-bottom: 5vw;
    }
    .hoverTable td{ 
      padding:7px; border:black 1px solid;
    }
    .hoverTable th{ 
      padding:7px; border:black 1px solid;
    }
    /* Define the default color for all the table rows */
    .hoverTable tr{
      background: #eee;
    }
    /* Define the hover highlight color for the table row */
      .hoverTable tr:hover {
            background-color: #b8d1f3;
      }
    
    #myCarousel{
      margin-bottom: 5vw;
    }

    table td:hover {
    background-color: rgba(0,0,0,.075);
    }

    #grade_form{
      margin-left: 70px;
      margin-right: 70px;

    }
    
    </style>

<script>
    $(document).ready(function(){
        $("#edit_form").hide();
      $("#edit_button").click(function(){
        $("#edit_form").toggle();
      });
    });
</script>

</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'index' %}">ClassTrail</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        {% if user.is_authenticated and user.is_teacher %}
        <li class="nav-item active"><a class="nav-link" href="{% url 'teacher_hub' %}">Teacher Hub</a></li>
        {% endif %}
        {% if user.is_authenticated and user.is_student %}
        <li class="nav-item active"><a class="nav-link" href="#">Student Hub</a></li>
        {% endif %}
        
      </ul>
      <span class="navbar-text">
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated%}
            <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
            {%else%}
            <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
            <li><a href="{% url 'register' %}"><span class="glyphicon glyphicon-log-in"></span> Register</a></li>
            {% endif %}
          </ul>
      </span>
    </div>
  </nav>



{% load crispy_forms_tags %}

<div id = "grade_form">
{% block content %}
<form action="" method="GET" enctype="multipart/form-data">

  {{ form|crispy }}

  <input type="submit" value="Submit">
</form>
{% endblock %}
</div>

{% for work in work_list.workdesc %}

<td ><a>{{ work.work_description }}</a></td>
{% empty %}
No Work Uploaded.
{% endfor %}

      <h5>Submitted:</h5>
      <table class="table table-bordered">
        <tbody>
          <tr>
            <th>Name:</th>
            <th>Uploaded at:</th>
          </tr>

            {% for work in work_list.submitted %}
            <tr>
              <td ><a href="{% url 'grade_work_item' work.id %}">{{ work.student.first_name }} {{ work.student.last_name }}</a></td>
              <td > {{ work.date}} {{ work.time_assigned}}</td>
            </tr>
            {% endfor %}

        </tbody>
      </table>

      <h5>Not submitted:</h5>
      <table class="table table-bordered">
        <tbody>

            {% for person in work_list.not_submitted %}
            <tr>
             <td>{{ person.user }}</td>
             {% if forloop.counter > 2 %}
              </tr>          
              {% endif %}

                


            {% endfor %}

        </tbody>
      </table>


</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
    <section>
        <div class="container">
          <div class="row">
            <div class="col-md-6 mx-auto">
              <div class="card">
 
                <div class="card-body">
                    <div class="row">
                       <div class="col-lg-6">
                         {% if user.is_authenticated%}
                         <h2>Welcome {{ user.first_name }}</h2>
                       {% endif %}
                      </div>
                       <div class="col-lg-6">
                       </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
{% endblock %}

templates/view_grades.html
{% extends 'base.html' %}
{% block content %}

    <div class="jumbotron">
        <div class="container text-center">
          <h1>View Grades</h1>      
        </div>
    </div>


{% for work in work_list %}

<ul id = "{{ work.get_classroom }}" class="list-group ">
    <li class="list-group-item bg-primary text-white">{{ work.classroom_subject }}</li>
        {% for workitem in work.workitem_set.all %}
            <li class="list-group-item"> {{ workitem.work_description }}
            {% for upload in workitem.userupload_set.all %}
                {% if user.id == upload.student_id %}
                    {% if upload.grade is Null %}
                        -----------Not graded yet
                    {% else %}
                ----------------------{{upload.grade}}
                {% endif %}
                {% endif %}
                {% empty %}
                ----------------No Work Uploaded.
        {% endfor %}
        {% endfor %}
    </li>
    <li class="list-group-item"> </li>
</ul>
</div><br><br>
{% endfor %}




</div><br>

</div><br><br>

{% endblock %}